// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6zbpLF9_v3qiQDgcL7o7oXlCvt4r-_e4',
    appId: '1:730853111991:web:455f8447eb6bd845a27532',
    messagingSenderId: '730853111991',
    projectId: 'raddittutorial',
    authDomain: 'raddittutorial.firebaseapp.com',
    storageBucket: 'raddittutorial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBOPTwFR8IUBYa_Ofxzp20TKnmjOaKLVw',
    appId: '1:730853111991:android:d648206e89f27777a27532',
    messagingSenderId: '730853111991',
    projectId: 'raddittutorial',
    storageBucket: 'raddittutorial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF7fXTGG4lm5oIwFMhAMS_MsI6kuAUQG0',
    appId: '1:730853111991:ios:3df1e315c6bcc8c5a27532',
    messagingSenderId: '730853111991',
    projectId: 'raddittutorial',
    storageBucket: 'raddittutorial.appspot.com',
    iosBundleId: 'com.example.radditTutorial',
  );
}
